# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_driver_pb2 as compute__driver__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputeDriverStub(object):
    """Internal compute-driver contract used by the gateway.

    Conventions:
    - This file owns driver-native request, response, and observation types.
    - Compute drivers must not import or return the public `openshell.v1.Sandbox`
    resource model.
    - The gateway translates between these internal driver-native messages and
    the public OpenShell API resource model.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/GetCapabilities',
                request_serializer=compute__driver__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ValidateSandboxCreate = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/ValidateSandboxCreate',
                request_serializer=compute__driver__pb2.ValidateSandboxCreateRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.ValidateSandboxCreateResponse.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/GetSandbox',
                request_serializer=compute__driver__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.GetSandboxResponse.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/ListSandboxes',
                request_serializer=compute__driver__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.CreateSandbox = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/CreateSandbox',
                request_serializer=compute__driver__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.StopSandbox = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/StopSandbox',
                request_serializer=compute__driver__pb2.StopSandboxRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.StopSandboxResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/openshell.compute.v1.ComputeDriver/DeleteSandbox',
                request_serializer=compute__driver__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)
        self.WatchSandboxes = channel.unary_stream(
                '/openshell.compute.v1.ComputeDriver/WatchSandboxes',
                request_serializer=compute__driver__pb2.WatchSandboxesRequest.SerializeToString,
                response_deserializer=compute__driver__pb2.WatchSandboxesEvent.FromString,
                _registered_method=True)


class ComputeDriverServicer(object):
    """Internal compute-driver contract used by the gateway.

    Conventions:
    - This file owns driver-native request, response, and observation types.
    - Compute drivers must not import or return the public `openshell.v1.Sandbox`
    resource model.
    - The gateway translates between these internal driver-native messages and
    the public OpenShell API resource model.
    """

    def GetCapabilities(self, request, context):
        """Report driver capabilities and defaults.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSandboxCreate(self, request, context):
        """Validate a sandbox before create-time provisioning.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """Fetch the platform-observed sandbox state for one sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """List platform-observed sandbox state for all sandboxes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandbox(self, request, context):
        """Provision platform resources for a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSandbox(self, request, context):
        """Stop platform resources for a sandbox without deleting its record.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Tear down platform resources for a sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSandboxes(self, request, context):
        """Stream sandbox observations from the platform.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=compute__driver__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=compute__driver__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'ValidateSandboxCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSandboxCreate,
                    request_deserializer=compute__driver__pb2.ValidateSandboxCreateRequest.FromString,
                    response_serializer=compute__driver__pb2.ValidateSandboxCreateResponse.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=compute__driver__pb2.GetSandboxRequest.FromString,
                    response_serializer=compute__driver__pb2.GetSandboxResponse.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=compute__driver__pb2.ListSandboxesRequest.FromString,
                    response_serializer=compute__driver__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=compute__driver__pb2.CreateSandboxRequest.FromString,
                    response_serializer=compute__driver__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'StopSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSandbox,
                    request_deserializer=compute__driver__pb2.StopSandboxRequest.FromString,
                    response_serializer=compute__driver__pb2.StopSandboxResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=compute__driver__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=compute__driver__pb2.DeleteSandboxResponse.SerializeToString,
            ),
            'WatchSandboxes': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSandboxes,
                    request_deserializer=compute__driver__pb2.WatchSandboxesRequest.FromString,
                    response_serializer=compute__driver__pb2.WatchSandboxesEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openshell.compute.v1.ComputeDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openshell.compute.v1.ComputeDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputeDriver(object):
    """Internal compute-driver contract used by the gateway.

    Conventions:
    - This file owns driver-native request, response, and observation types.
    - Compute drivers must not import or return the public `openshell.v1.Sandbox`
    resource model.
    - The gateway translates between these internal driver-native messages and
    the public OpenShell API resource model.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/GetCapabilities',
            compute__driver__pb2.GetCapabilitiesRequest.SerializeToString,
            compute__driver__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSandboxCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/ValidateSandboxCreate',
            compute__driver__pb2.ValidateSandboxCreateRequest.SerializeToString,
            compute__driver__pb2.ValidateSandboxCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/GetSandbox',
            compute__driver__pb2.GetSandboxRequest.SerializeToString,
            compute__driver__pb2.GetSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/ListSandboxes',
            compute__driver__pb2.ListSandboxesRequest.SerializeToString,
            compute__driver__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/CreateSandbox',
            compute__driver__pb2.CreateSandboxRequest.SerializeToString,
            compute__driver__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/StopSandbox',
            compute__driver__pb2.StopSandboxRequest.SerializeToString,
            compute__driver__pb2.StopSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/DeleteSandbox',
            compute__driver__pb2.DeleteSandboxRequest.SerializeToString,
            compute__driver__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openshell.compute.v1.ComputeDriver/WatchSandboxes',
            compute__driver__pb2.WatchSandboxesRequest.SerializeToString,
            compute__driver__pb2.WatchSandboxesEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
