"""OpenShell compute provider — wraps NVIDIA OpenShell gRPC.

Stub for Week 1. Fully implemented in Week 2 when gRPC stubs are generated
via ``make vendor-protos && make proto-gen``.

Critical invariants enforced here:
  - Every CreateSandbox call adds label ``shellforge.io/tenant=<tenant_id>``
  - Every ListSandboxes call adds label_selector for the requesting tenant
  - GetSandboxProviderEnvironment is NEVER called from the control plane
"""

from __future__ import annotations

from typing import AsyncIterator

from src.config import Settings
from src.interfaces.compute_provider import (
    ComputeProvider,
    SandboxEvent,
    SandboxLogLine,
    SandboxRef,
    SandboxSpec,
)


TENANT_LABEL_KEY = "shellforge.io/tenant"


class OpenShellComputeProvider(ComputeProvider):
    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        # gRPC channel + stub initialized lazily in Week 2.
        # Stubs generated by `make proto-gen` into
        # src/openshell/proto/openshell_pb2{,_grpc}.py

    async def create_sandbox(self, tenant_id: str, spec: SandboxSpec) -> SandboxRef:
        raise NotImplementedError("OpenShell compute provider implemented in Week 2.")

    async def get_sandbox(self, tenant_id: str, name: str) -> SandboxRef:
        raise NotImplementedError

    async def list_sandboxes(self, tenant_id: str) -> list[SandboxRef]:
        raise NotImplementedError

    async def delete_sandbox(self, tenant_id: str, name: str) -> None:
        raise NotImplementedError

    async def apply_policy(self, tenant_id: str, name: str, policy_yaml: str) -> None:
        raise NotImplementedError

    async def watch_sandbox(
        self, tenant_id: str, name: str
    ) -> AsyncIterator[SandboxEvent]:
        raise NotImplementedError
        yield  # type: ignore[unreachable]

    async def tail_logs(
        self, tenant_id: str, name: str
    ) -> AsyncIterator[SandboxLogLine]:
        raise NotImplementedError
        yield  # type: ignore[unreachable]

    async def create_provider(
        self,
        tenant_id: str,
        name: str,
        provider_type: str,
        credentials: dict[str, str],
    ) -> None:
        raise NotImplementedError
